class VjCatalog {
  const VjCatalog._();

  static const names = [
    'VJ JUNIOR',
    'VJ EMMY',
    'VJ ICE P',
    'VJ JINGO',
    'VJ JULIO',
    'VJ MARK',
    'VJ SOUL',
    'VJ SHIELD',
    'VJ KEVO',
    'VJ KRISS S',
    'VJ TONNY',
    'VJ UNCLE T',
    'VJ NELLY',
    'VJ NEIL',
    'VJ HAM',
    'VJ NEIMA',
    'VJ BANKS',
    'VJ TOM',
    'VJ LITTLE T',
    'VJ RYAN',
    'VJ FREDY',
    'VJ KALI',
    'VJ PHOENIX',
    'VJ MOSCO',
    'VJ BAROS',
    'VJ RONAGE',
    'VJ HEAVY Q',
    'VJ ILLESS',
    'VJ KK THE BEST',
    'VJ 03',
    'VJ AARON',
    'VJ AKAANA',
    'VJ ARAFA',
    'VJ ARTIK',
    'VJ ASHIM',
    'VJ CABS',
    'VJ CB',
    'VJ DAN DE',
    'VJ EDDY',
    'VJ BONNY',
    'VJ HD',
    'VJ HEAVY K',
    'VJ HENRICO',
    'VJ ISMA K',
    'VJ ISMA PRO',
    'VJ IVO',
    'VJ JIMMY',
    'VJ JOE',
    'VJ JONA',
    'VJ JOVAN',
    'VJ JOZZ',
    'VJ JUMPERS',
    'VJ KAM',
    'VJ KEVIN',
    'VJ KHAN LI',
    'VJ KIMULI',
    'VJ KIN',
    'VJ KS',
    'VJ LANCE',
    'VJ LASH',
    'VJ LIGHT',
    'VJ MARTIN K',
    'VJ MAYANJA',
    'VJ MK',
    'VJ MOX',
    'VJ MUBA',
    'VJ MUK',
    'VJ MUSA',
    'VJ OTC',
    'VJ PAULETA',
    'VJ PAX',
    'VJ RODDY',
    'VJ RONNIE',
    'VJ SAMMY',
    'VJ SHAO K',
    'VJ SHARZ',
    'VJ SHIVO',
    'VJ SON',
    'VJ VOLOCANO',
    'VJ WAZA',
    'VJ ZAIDI',
  ];

  static String labelForSeed(int seed) {
    final index = seed.abs() % names.length;
    return names[index];
  }
}
